-- MySQL Script generated by MySQL Workbench
-- Fri Apr  4 20:54:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_tutoriza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tutoriza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tutoriza` DEFAULT CHARACTER SET utf8 ;
USE `db_tutoriza` ;

-- -----------------------------------------------------
-- Table `db_tutoriza`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tutoriza`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tutoriza`.`assessorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tutoriza`.`assessorias` (
  `id` INT NOT NULL,
  `duracao` VARCHAR(45) NOT NULL,
  `tema` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `notas` MEDIUMTEXT NULL,
  `tutor` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assessorias_usuarios_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_assessorias_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_tutoriza`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
